# Generated by Django 4.1.7 on 2025-06-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_initial'),
        ('images', '0004_image_category_id_image_colors'),
        ('community', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='相册'),
        ),
    ]
