# Generated by Django 4.1.7 on 2025-06-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_initial'),
        ('community', '0005_comment_image_alter_comment_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='相册'),
            preserve_default=False,
        ),
    ]
