# Generated by Django 4.1.7 on 2025-01-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('community', '0006_remove_comment_image_alter_comment_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album', verbose_name='相册'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='图片'),
        ),
    ] 