# Generated by Django 4.1.7 on 2025-07-01 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_ai_emotion_analysis_image_ai_style_analysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0007_add_image_to_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='images.image', verbose_name='图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'image')},
            },
        ),
    ]
