# Generated by Django 4.1.7 on 2025-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_image_category_id_image_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="ai_description",
            field=models.TextField(blank=True, null=True, verbose_name="AI智能分析"),
        ),
    ]
