# Generated by Django 4.1.7 on 2025-07-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ai_emotion_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI情感分析'),
        ),
        migrations.AddField(
            model_name='image',
            name='ai_style_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI风格分析'),
        ),
        migrations.AddField(
            model_name='image',
            name='user_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='用户自定义标签'),
        ),
    ]
