# Generated by Django 4.1.7 on 2025-07-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_ai_emotion_analysis_image_ai_style_analysis_and_more'),
    ]

    operations = [
    ]
