# Generated by Django 4.1.7 on 2025-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20250701_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='image',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地点名称'),
        ),
        migrations.AddField(
            model_name='image',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
