# Generated by Django 4.1.7 on 2025-07-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_latitude_image_location_name_image_longitude'),
    ]

    operations = [
    ]
