# Generated by Django 4.1.7 on 2025-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20250702_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='审核通过'),
        ),
    ]
