# Generated by Django 4.1.7 on 2025-06-26 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_manage_tags',
            field=models.BooleanField(default=False, verbose_name='标签管理权限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_templates',
            field=models.BooleanField(default=False, verbose_name='模型管理权限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='用户管理权限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_statistics',
            field=models.BooleanField(default=False, verbose_name='数据查看权限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否验证'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('admin', '管理员'), ('moderator', '版主')], default='user', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
